timesheet/timesheet/urls.py
from django.contrib import admin
from django.urls import path
from website.views import logmein, logmeout, search, home
from website.views.user import myUser, createUser, deleteUser
from website.views.timesheet import timesheet, getTimesheetById, timesheetXml
from website.views.totp import checkTotp

urlpatterns = [
    path('e44002bf-8b73-4827-8a27-f62326e868d0-admin/', admin.site.urls),
    path('login', logmein, name="login"),
    path('home', home, name="home"),
    path('logout', logmeout, name="logout"),
    path('myUser', myUser, name="myUser"),
    path('createUser', createUser, name="createUser"),
    path('deleteUser', deleteUser, name="deleteUser"),
    path('timesheets', timesheet, name="timesheets"),
    path('timesheetsXml', timesheetXml, name="timesheetsXml"),
    path('timesheets/<int:id>', getTimesheetById, name="getTimesheetById"),
    path('timesheets/search', search, name="searchResults"),
    path('login/totpSetup', checkTotp, name="totpSetup"),
]

timesheet/website/models/createUser.py
from django.db import models

class CreateUser(models.Model):
    username = models.CharField(max_length=30)
    email = models.CharField(max_length=50)
    password = models.CharField(max_length=30)

timesheet/website/models/credentials.py
from django.db import models

class Credentials(models.Model):
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=20)

timesheet/website/models/logEntry.py
import datetime

class LogEntry:
    def __init__(self, action, user='', ipAddress=''):
        self.action = action
        self.ipAddress = ipAddress
        self.user = user

    def __str__(self):
        return '{0} - {1} - {2}'.format(self.action, self.ipAddress, self.user)

timesheet/website/models/timesheet.py
from django.db import models

class Timesheet(models.Model):
    id = models.IntegerField(primary_key=True, unique=True, editable=False)
    userId = models.IntegerField()
    date = models.DateField()
    timeFrom = models.TimeField()
    timeTo = models.TimeField()
    totalMinutes = models.IntegerField()
    approved = models.BooleanField(default=False)
    notes = models.CharField(max_length=200)

timesheet/website/models/totp.py
from django.db import models
from django_cryptography.fields import encrypt

class Totp(models.Model):
    userId = models.IntegerField()
    secret = encrypt(models.CharField(max_length=32))

timesheet/website/models/userDetails.py
from django.db import models

class UserDetails(models.Model):
    userId = models.IntegerField()
    hourlyRate = models.IntegerField()
    phone = models.CharField(max_length=20)
    routingNumber = models.CharField(max_length=30)
    accountNumber = models.CharField(max_length=30)
    chargeToClientRate = models.DecimalField(decimal_places=2, max_digits=6, default=500)

timesheet/website/forms/createUserForm.py
from django import forms
from django.forms import Form, CharField, PasswordInput
from django.contrib.auth.password_validation import validate_password

class CreateUserForm(forms.Form):
    username = CharField(max_length=30)
    email = CharField(max_length=50)
    password = CharField(widget=PasswordInput())

    def clean_password(self):
        password = self.cleaned_data.get('password')
        try:
            validate_password(password, self)
        except forms.ValidationError as error:
            self.add_error('password', error)
        return password

timesheet/website/forms/deleteUserForm.py
from django import forms
from django.forms import CharField

class DeleteUserForm(forms.Form):
    username = CharField(max_length=30)

timesheet/website/forms/loginForm.py
from django.forms import Form, CharField, PasswordInput

class LoginForm(Form):
    username = CharField(max_length=20)
    password = CharField(widget=PasswordInput())
    totp = CharField(max_length=6)

timesheet/website/forms/myUserForm.py
from django.forms import ModelForm, TextInput, HiddenInput
from website.models import UserDetails 

class MyUserForm(ModelForm):
    class Meta:
        model = UserDetails 
        fields = ('userId', 'phone', 'routingNumber', 'accountNumber')
        widgets = {
            'userId': HiddenInput(),
            'phone': TextInput(),
            'routingNumber': TextInput(),
            'accountNumber': TextInput(),
        }

timesheet/website/forms/searchTimesheetForm.py
from django.forms import Form, CharField

class SearchTimesheetForm(Form):
    searchText = CharField(max_length=30)

timesheet/website/forms/timesheetForm.py
from django.forms import ModelForm, TextInput, HiddenInput, DateInput, TimeInput, CheckboxInput
from website.models.timesheet import Timesheet 

class TimesheetForm(ModelForm):
    class Meta:
        model = Timesheet 
        fields = ['date', 'userId', 'timeFrom', 'timeTo', 'notes', 'totalMinutes', 'approved']
        widgets = {
            'userId': HiddenInput(),
            'date': DateInput(attrs={"type":"date"}),
            'timeFrom': TimeInput(attrs={'type': 'time'}),
            'timeTo': TimeInput(attrs={'type': 'time'}),
            "notes": TextInput(attrs={'size':100, 'maxlength':200}),
            'totalMinutes': HiddenInput(),
        }

timesheet/website/forms/timesheetXmlForm.py
from django.forms import Form, CharField, Textarea

class TimesheetXmlForm(Form):
    xmlData = CharField(widget=Textarea(attrs={'cols': 77, 'rows': 15}), max_length=4096)

timesheet/website/views/authentication.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from website.forms import LoginForm
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from website.views.totp import validateTotp
from website.models.logEntry import LogEntry
import logging

logger = logging.getLogger(__name__)

@csrf_exempt
@login_required(login_url='/login')
def logmeout(request):
    logout(request)
    return redirect('/login')

@csrf_exempt
def logmein(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            totp = request.POST['totp']
            user = authenticate(username=username, password=password, request=request)
            if user is not None:
                if validateTotp(request, user.id, totp):
                    login(request, user)
                    return redirect("/home")
                else:
                    ip = request.META.get('REMOTE_ADDR')
                    logger.warning(LogEntry(action='on_login_fail_totp', ipAddress=ip, user=username))
                    return HttpResponse("Incorrect TOTP")
            else:
                ip = request.META.get('REMOTE_ADDR')
                logger.warning(LogEntry(action='on_login_fail', ipAddress=ip, user=username))
                return HttpResponse("login failed")
    else:
        form = LoginForm()
    
    return render(request, "website/login.html", {"form": form})

timesheet/website/views/home.py
from django.shortcuts import render

def home(request):
    return render(request, 'website/home.html')

def anon(request):
    return render(request, 'website/anon.html')

timesheet/website/views/searchTimesheet.py
from django.shortcuts import render, redirect
from website.models.timesheet import Timesheet
from django.contrib.auth.decorators import login_required

@login_required(login_url='/login')
def search(request):
    searchText = request.GET.get('searchText')
    if not searchText is None:
        searchTimesheets = Timesheet.objects.filter(notes__contains=searchText)
        return render(request, 'website/searchTimesheet.html', {'searchResults': searchTimesheets, "searchText": searchText})

    return render(request, 'website/searchTimesheet.html')

timesheet/website/views/timesheet.py
from django.shortcuts import render, HttpResponse
from website.forms.timesheetForm import TimesheetForm
from website.forms.timesheetXmlForm import TimesheetXmlForm
from website.models.timesheet import Timesheet
from datetime import date, datetime, timedelta
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from lxml import etree
from django.utils.dateparse import parse_date

@login_required(login_url="/login")
def getTimesheetById(request, id):
    timesheet = Timesheet.objects.get(id=id)
    form = TimesheetForm(initial=timesheet.__dict__)
    return render(request, "website/timesheet.html", {"form": form})

@csrf_exempt
@login_required(login_url="/login")
def timesheet(request):
    if request.method == "POST":
        return postTimesheet(request)

    now = datetime.now()
    form = TimesheetForm(initial=
        {
            "userId":request.user.id, 
            "approved": False, 
            "date": date.today(),
            "timeFrom": (now + timedelta(hours=-1)).strftime("%H:%M"),
            "timeTo": now.strftime("%H:%M"),
            "totalMinutes": 0
        })
    return render(request, "website/timesheet.html", {"form": form})

@login_required(login_url="/login")
def postTimesheet(request):
    form = TimesheetForm(request.POST)
    if form.is_valid():
        if allowApprove(request):
            form.save()
        else:
            timesheet = form.save(commit=False)
            timesheet.approved = False
            timesheet.save()

    return render(request, "website/timesheet.html", {"form": form})

@login_required(login_url="/login")
def timesheetXml(request):
    if request.method == "POST":
        return postTimesheetXML(request)

    now = datetime.now()
    form = TimesheetXmlForm()
    return render(request, "website/timesheetXml.html", {"form": form})

@login_required(login_url="/login")
def postTimesheetXML(request):
    root = ""
    if request.method=="POST":
        data = request.POST["xmlData"]
        parser = etree.XMLParser(resolve_entities=False)
        root = etree.fromstring(data, parser=parser)

        timesheet = Timesheet()
        timesheet.date = parse_date(root.find("date").text)
        timesheet.timeFrom = root.find("timeFrom").text
        timesheet.timeTo = root.find("timeTo").text
        timesheet.notes = root.find("notes").text
        timesheet.userId = root.find("userId").text
        timesheet.totalMinutes = root.find("totalMinutes").text
        timesheet.approved = False
        timesheet.save()

    return HttpResponse(etree.tostring(root))

def allowApprove(request):     
    if request.user.has_perm("website.approve_timesheet"):
        return True
    else:
        return False

timesheet/website/views/totp.py
from django.shortcuts import HttpResponse, redirect
from django.contrib.auth.decorators import login_required
from website.models.totp import Totp
from io import BytesIO
import pyotp
import base64
import qrcode

@login_required(login_url='/login')
def checkTotp(request):
    if request.method == "POST":
        totp = request.POST['totp']
        if validateTotp(request, request.user.id, totp):
            return redirect("/home")
        else:
            return HttpResponse("Wrong TOTP")

def validateTotp(request, userId, submittedTotp):
    userTotpRecord = Totp.objects.get(userId=userId)
    totp = pyotp.TOTP(userTotpRecord.secret)
    currentTotp = totp.now()
    if submittedTotp == currentTotp:    
        request.session['MfaAccepted'] = True
    else:
        request.session['MfaAccepted'] = False

    return request.session['MfaAccepted']

def totpBase64Image(secret, email):
    uri = pyotp.totp.TOTP(secret).provisioning_uri(name=email, issuer_name='TimesheetApp')
    img = qrcode.make(uri)
    output_buffer = BytesIO()
    img.save(output_buffer, format='PNG')
    binary_data = output_buffer.getvalue()
    base64_data = base64.b64encode(binary_data)
    return 'data:image/png;base64,' + base64_data.decode()

def newTotp(user):
    secret = pyotp.random_base32()
    totp = Totp(userId=user.id, secret=secret)
    totp.save()
    return totp

timesheet/website/views/user.py
from django.contrib.auth.models import User, Group
from django.shortcuts import render, HttpResponse
from website.forms.myUserForm import MyUserForm
from website.forms.createUserForm import CreateUserForm
from website.forms.deleteUserForm import DeleteUserForm
from website.models.userDetails import UserDetails
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from website.views.totp import newTotp, totpBase64Image
from website.decorators import logged_permission_required

@login_required(login_url="/login")
def myUser(request):
    currentUser = UserDetails.objects.get(userId=request.user.id)
    if request.method == "POST":
        form = MyUserForm(request.POST, instance=currentUser)
        if form.is_valid():
            form.save()
    else:
        form = MyUserForm(initial=vars(currentUser))

    return render(request, "website/myUser.html", {"form": form})

@logged_permission_required(permission="auth.delete_user")
def deleteUser(request):
    if request.method == "POST":
        form = DeleteUserForm(request.POST)
        try:
            username = request.POST['username']
            userRecord = User.objects.get(username=username)
            userRecord.delete()
            return render(request, "website/message.html", {"message": "User deleted"})
        except Exception as e:
            return render(request, "website/deleteUser.html", {"message": str(e), "form": form})
    else:
        form = DeleteUserForm()

    return render(request, "website/deleteUser.html", {"form": form})

def createUser(request):
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            username = request.POST["username"]
            email = request.POST["email"]
            password = request.POST["password"]
            user = User.objects.create_user(username, email, password) 
            addToGroup(user, "TimesheetUsers") 
            userDetails = UserDetails(userId=user.id, hourlyRate=5, phone="", routingNumber = "", accountNumber="")
            userDetails.save()
            login(request, user, backend="django.contrib.auth.backends.ModelBackend")

            totp = newTotp(user)
            base64Image = totpBase64Image(totp.secret, email)
            return render(request, "website/totpSetup.html", {"base64Image": base64Image})
    else:
        form = CreateUserForm()

    return render(request, "website/createUser.html", {"form": form})

def addToGroup(user, groupName):
    timesheetUsersGroup = Group.objects.get(name=groupName) 
    user.groups.add(timesheetUsersGroup)

timesheet/website/templates/website/anon.html
{% extends "base.html" %}

{% block title %}{% endblock %}

{% block content %}

Hello anon

{% endblock %}

timesheet/website/templates/website/createUser.html
{% extends "base.html" %}

{% block title %}Create User{% endblock %}

{% block content %}

<form method="POST">
    <table>
        {{form}}
    </table>
    {% csrf_token%}
    <button type="submit">Create</button>
</form>

{% endblock %}

timesheet/website/templates/website/deleteUser.html
{% extends "base.html" %}

{% block title %}Create User{% endblock %}

{% block content %}

<form method="POST">
    {{message}}
    <table>
        {{form}}
    </table>
    {% csrf_token%}
    <button type="submit">Delete</button>
</form>

{% endblock %}

timesheet/website/templates/website/home.html
{% extends "base.html" %}

{% block title %}{% endblock %}

{% block content %}


{% endblock %}

timesheet/website/templates/website/login.html
{% extends "base.html" %}

{% block title %}{% endblock %}

{% block content %}

<form method="POST">
    <table>
        {{form}}
    </table>
    {% csrf_token%}
    <button type="submit">Login</button>
</form>

{% endblock %}

timesheet/website/templates/website/message.html
{% extends "base.html" %}

{% block title %}Message{% endblock %}

{% block content %}

{{message}}

{% endblock %}

timesheet/website/templates/website/myUser.html
{% extends "base.html" %}

{% block title %}User{% endblock %}

{% block content %}

<form method="POST">
    <table>
        {{form}}
    </table>
    {% csrf_token%}
    <button type="submit">Update</button>
</form>

{% endblock %}

timesheet/website/templates/website/rateLimit.html
{% extends "base.html" %}

{% block title %}Rate Limit Exceeded{% endblock %}

{% block content %}

You have failed to login {{failure_limit}} times <BR><BR>

Your account is now locked for {{cooloff_timedelta}} minutes.

{% endblock %}

timesheet/website/templates/website/searchTimesheet.html
{% extends "base.html" %}

{% block title %}Search Timesheet{% endblock %}

{% block content %}



<form method="GET">
    <table>
        <tr>
            <td>search: <input type="text" id="searchText" name="searchText" size="60" autocomplete="off"> </td>
            <td><button type="submit">Search</button></td>
        </tr>
    </table>
</form>

<br><br>


{% if searchResults %}
<table>
    There are {{ searchResults|length }} record(s) for "{{searchText}}":
    {% for searchResult in searchResults %}
        <tr><td><a href="/timesheets/{{searchResult.id}}">{{searchResult.notes}}</a></td></tr>
    {% endfor %}
</table>
{% else %}
    There are 0 records for "{{searchText}}":
{% endif %}
 


{% endblock %}

timesheet/website/templates/website/timesheet.html
{% extends "base.html" %}

{% block title %}Timesheet{% endblock %}

{% block content %}
<form method="POST">
    <table>
        {{form}}
    </table>
    
    <button type="submit">Add / Update</button>
    {% csrf_token%}
</form>
{% endblock %}

{% block scripts %}
<script src="/static/js/timesheet.js"></script>
{% endblock %}

timesheet/website/templates/website/timesheetXml.html
{% extends "base.html" %}

{% block title %}Timesheet{% endblock %}

{% block content %}
<form method="POST">
    <table>
        {{form}}
    </table>
    
    <button type="submit">Add</button>
    {% csrf_token%}
</form>
{% endblock %}

{% block scripts %}
<script>
    
    if (getCookie('permissions').includes('allowApprove'))
    {
        $("#id_approved").css("visibility", "visible");
        $("#id_approved" ).prop( "checked", true );
    }
    else
    {
        $('label[for="id_approved"]').css("visibility", "hidden")
    }
</script>
{% endblock %}

timesheet/website/templates/website/totpSetup.html
{% extends "base.html" %}

{% block title %}TOTP Setup{% endblock %}

{% block content %}

Please use an authenticator app to scan this image and complete your time-based one-time Password (TOTP) setup
<img src="{{ base64Image }}" />'

<form method="POST" action="login/totpSetup">
    <table>
        Enter number from TOTP app to confirm successful registration: <br>
        <input type="text" name="totp" id="totp">
    </table>
    
    <button type="submit">Confirm</button>
    {% csrf_token%}
</form>

{% endblock %}